### ISSUE TITLE
Snowpack build dist

### ISSUE THREAD

**Issue by mvillafuertem** [lolgab/scalajs-snowpack-example#1]
Hey @lolgab , 
I just saw your video tutorial. Amazing work!!. can you explain how build  dist with scalajs + Snowpack?. Thanks

**Comment by lolgab** [comment]
Hi @mvillafuertem,
Thank you!
Can you elaborate?

**Comment by mvillafuertem** [comment]
If you give me some hints I can work in this. In some situations I use scalajs-bundler to build dist. something like this https://github.com/ScalablyTyped/ScalaJsReactDemos/blob/master/build.sbt#L358

**Comment by lolgab** [comment]
@mvillafuertem Hi :)
I just revived this project and converted it to Mill (my main build tool).
Now it has commands for both development and production.
By build _dist_ you mean the final files to distribute, right?
If so, this issue can probably be closed as solved.

**Comment by mvillafuertem** [comment]
Hi @lolgab, looks really nice. I have never use mill, maybe it's a good time to start. 
I just saw that Snowpack is no longer actively maintained. 🥲

**Comment by lolgab** [comment]
>  I just saw that Snowpack is no longer actively maintained. 🥲

Since they suggest using Vite instead I can migrate this example to Vite.

**Comment by mvillafuertem** [comment]
> Since they suggest using Vite instead I can migrate this example to Vite.

Yeah, it would be nice. Thanks

**Comment by lolgab** [comment]
@mvillafuertem I migrated the example to Vite: https://github.com/lolgab/scalajs-vite-example
It also uses Mill `0.10.4` with `ModuleSplitStyle.SmallModulesFor` for a faster loop.
